### ISSUE TITLE
Cannot resolve module 'expose'

### ISSUE THREAD

**Issue by ghost** [unindented/ulmus-loader#1]
I've tried using ulmus as a preLoader like proposed in the example (why is it needed, btw?), but I keep getting this error message complaining about the syntax presented:

In my make-webpack-config.js I have:

``` javascript
            preLoaders: [{
                test: /\.elm$/,
                exclude: /node_modules/,
                loader: 'expose?Elm!exports?Elm!ulmus?output=dist/[name].js'
            }],
```

In my to level webpackconfig.js for dev I have:

``` javascript
module.exports = require('./make-webpack-config.js')(
    {
        debug: true,
        entry: ['webpack/hot/dev-server', './src/elm/Bingo.elm', './entry.js'],
        output: {
            path: path.resolve(__dirname, 'build'),
            filename: "bundle.js"
        }
    }
);
```

or, I require "Bingo.elm" in entry.js instead. Both fail like this:

``` shell

npm run rebuild

> elm-bingo@0.0.1 rebuild /Users/uri/Projects/elm/elm-bingo
> $(npm bin)/webpack --config=webpack.config.dev.js --color --progress

Hash: d08bfb8b9aad1dd09897  
Version: webpack 1.10.5
Time: 980ms
    Asset     Size  Chunks             Chunk Names
bundle.js  45.6 kB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
   [2] ./entry.js 64 bytes {0} [built] [1 error]
    + 5 hidden modules

ERROR in ./entry.js
Module not found: Error: Cannot resolve module 'expose' in /Users/uri/Projects/elm/elm-bingo
 @ ./entry.js 2:0-30
```

**Comment by ghost** [comment]
Ok, I now have something like this, which compiles just fine, but only will create ./dist/Bingo.js, and ignore everything else, like the stylesheets, which get bundled if I don't require "Bingo.elm" in my entry module...

``` javascript
...
            loaders: [
                { test: /\.css$/,
                  loader: 'style!css'
                },
                {
                    test: /\.elm$/,
                    exclude: /node_modules/,
                    loader: 'ulmus'
                }
            ]
       },
        ulmus: {
            output: './dist/[name].js'
        },

```

**Comment by unindented** [comment]
You should probably create a small example app that exposes the issue you are having. The original error you were seeing about `expose` just means you didn't add `expose-loader` to your list of dev dependencies.

I'm going to close this issue, as it seems to be a problem with your webpack configuration, rather than a problem with this loader.

Feel free to open a new issue describing a specific problem with the loader.

**Comment by ghost** [comment]
No problem. I've just realized that and already using it in my configuration, but seem to be running into other problems actually accessing methods on the variables, which is now indeed on the global scope.
10x

**Comment by ghost** [comment]
PS, what does 'exports' in "'expose?Elm!exports?Elm!'" actually refers to...?

**Comment by unindented** [comment]
@usharf All those things refer to loaders, so `expose` is referring to [`expose-loader`](https://github.com/webpack/expose-loader), `exports` to [`exports-loader`](https://github.com/webpack/exports-loader), etc.

In the example, I'm using them to both export and expose the global variable `Elm` that is present in files generated by the Elm compiler.

You can read more about loaders in general here: http://webpack.github.io/docs/loaders.html

**Comment by ghost** [comment]
I'm still figuring this thing out, thanks for the references!
I was able to make some progress with elm-webpack-loader, where by I'm using the following configuration. While with ulmus, I'm seeing an error when on `Elm.fullscreen`, though Elm itself becomes available on the global scope (which it didn't before of course).

``` javascript
        module: {
            loaders: [
                { test: /\.css$/,
                  loader: 'style!css'
                },
                {
                    test: /\.elm$/,
                    loader: 'elm-webpack'
                }
            ]
        },
```

and requiring like this:

``` javascript
require('./css/style.css');
require('expose?Elm!./elm/Bingo.elm');
```
