### ISSUE TITLE
usage with webpack --watch

### ISSUE THREAD

**Issue by tcoopman** [unindented/ulmus-loader#4]
Thank you for this loader, it is nice!

I was wondering if it was possible to use this loader with _webpack --watch_. At the moment this doesn't seem to work yet. Only if you change the entry file, a recompile is triggered.
You can tell webpack about the other files that are needed for the compilation and webpack will watch these too. See https://webpack.github.io/docs/how-to-write-a-loader.html#mark-dependencies

**Comment by unindented** [comment]
Thanks @tcoopman! Yup, I'm aware of webpack's `addDependency` method. The problem is that I don't know how to get the list of dependencies from the Elm compiler. Do you?

**Comment by tcoopman** [comment]
I've looked at it. But it's also not clear for me at the moment.
Although an other option may be possible. We could pass all known elm files
at the start to webpack. It's a bit naive and it will require a restart for
new files but it might be good enough.

**Comment by unindented** [comment]
@tcoopman I don't think that's a good solution, no other webpack loader works like that.

@evancz Is there any way we can get access to the tree of dependencies loaded by Elm when compiling a file?

**Comment by tcoopman** [comment]
@unindented I agree that it's not a conventional solution, but it's something that could work as long as there is no other solution.
At the moment, this loader has no value when using with `--watch` because of this.

**Comment by unindented** [comment]
@tcoopman Pull requests are welcome :wink:

**Comment by evancz** [comment]
There's not a flag to get that info, but I'm planning to expose that information in a future release. `elm-reactor` just keeps compiling the root module when Elm files change. It's not ideal, but it gets the job done. I think @rtfeldman did a custom thing for his build tools that actually figures out the deps though. Not sure if open source (lots to do!) but I don't think it's too crazy to write from scratch.

Also, why Ulmus and not Elm? I know it's the latin name or something, but does anyone else on the internet? I use a pretty strict "literal names" policy for all my Elm stuff (elm-make, elm-package, elm-html, elm-http, etc.) and I haven't seen the downside yet.

**Comment by tcoopman** [comment]
@evancz I think that's because there is already a package elm-webpack-loader (https://github.com/rtfeldman/elm-webpack-loader) but I'm not sure about that.

**Comment by unindented** [comment]
@evancz It was to avoid a name collision with this package: https://www.npmjs.com/package/elm-loader

There's also @rtfeldman's loader: https://www.npmjs.com/package/elm-webpack-loader (we should probably just merge the two; it's not like there's a ton of space for innovation in a webpack loader)

**Comment by evancz** [comment]
Yeah, talk with him. I don't think he's maintaining it for now. Makes sense to merge the projects. Maybe best thing is to delete @rtfeldman's and rename this one to `elm-webpack-loader`?

(Also, it's namespaced by user, which I think is going to be more of a thing in Elm. Not sure yet. Anyway, it's fine to do a rename now. The one with more stars and links will win, so just make the better one :P)

**Comment by rtfeldman** [comment]
For what it's worth, I'm actually working on [rtfeldman/elm-webpack-loader](https://github.com/rtfeldman/elm-webpack-loader) again (after 8 months of inactivity, heh) because we're finally moving to webpack at work. :smile_cat: 

As for `addDependencies`, I implemented that [in Ruby for Sprockets integration](https://gist.github.com/rtfeldman/db7b121100b6c6ff435b), so all that has to be done there is porting that logic over to JS.

**Comment by evancz** [comment]
Ah, cool, did not know that! Okay, it sounds like the things that need to be known are known now, so I'm going to unsubscribe from this. CC me if needed again!

**Comment by unindented** [comment]
Knowing that @rtfeldman is going to be working on his loader, I think I'd rather abandon mine and contribute to his.
